name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # the branch that is deployed from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'  # version I am using

    - name: Install dependencies
      run: npm install
      working-directory: ./my-portfolio

    - name: Build
      run: npm run build
      working-directory: ./my-portfolio

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages  # branch to deploy to
        FOLDER: my-portfolio/build  # folder to deploy
        CLEAN: true
